version: 3

services:
  mongo:
    image: mongo
    volumes:
      - /data/db/mongo
    ports:
      - '27017:27017'

  redis:
    image: redis:alpine
    volumes:
      - /data/db/redis
    ports:
      - '6379:6379'

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      PGDATA: /data/db/postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
